# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(712, 501)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.custom_qlr_file = QgsFileWidget(Frame)
        self.custom_qlr_file.setGeometry(QtCore.QRect(30, 120, 651, 71))
        self.custom_qlr_file.setObjectName("custom_qlr_file")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 651, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Extend the AusMap plugin with a custom QLR file"))
        self.custom_qlr_file.setFilter(_translate("Frame", "QLR (*.qlr)"))
        self.label_2.setText(_translate("Frame", "The layers in the Layer Definition file (.qlr) will be added as additional categories inside the AusMap plugin menu."))
from qgsfilewidget import QgsFileWidget
